name: ezkl-lib-release
on:
  push:
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-musl
          toolchain: stable
          override: true

      - name: Install Cross
        run: cargo install cross

      - name: Build Release
        run: cross build --target x86_64-unknown-linux-musl --release

      - name: Archive
        id: archive
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          mv target/x86_64-unknown-linux-musl/release/ezkl ezkl-$VERSION-x86_64-unknown-linux-musl
          tar czvf ezkl-$VERSION-x86_64-unknown-linux-musl.tar.gz ezkl-$VERSION-x86_64-unknown-linux-musl
          echo "::set-output name=path::$(pwd)/ezkl-$VERSION-x86_64-unknown-linux-musl.tar.gz"

      - name: Create Release
        run: |
          gh release create $VERSION --title "Release $VERSION" --notes "Release $VERSION"
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Upload Release Asset
        run: |
          gh release upload $VERSION ${{ steps.archive.outputs.path }}
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-pc-windows-msvc
          toolchain: stable
          override: true

      - name: Build Release
        run: cargo build --target x86_64-pc-windows-msvc --release

      - name: Archive
        id: archive
        shell: pwsh
        run: |
            $VERSION=$env:GITHUB_REF -replace 'refs/tags/', ''
            mv target/x86_64-pc-windows-msvc/release/ezkl_lib.exe ezkl_lib-$VERSION-x86_64-pc-windows-msvc.exe
            7z a ezkl_lib-$VERSION-x86_64-pc-windows-msvc.zip ezkl_lib-$VERSION-x86_64-pc-windows-msvc.exe
            echo "::set-output name=path::$(pwd)/ezkl_lib-$VERSION-x86_64-pc-windows-msvc.zip"

      - name: Create Release
        run: |
          gh release create $VERSION --title "Release $VERSION" --notes "Release $VERSION"
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Upload Release Asset
        run: |
          gh release upload $VERSION ${{ steps.archive.outputs.path }}
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-apple-darwin
          toolchain: stable
          override: true

      - name: Build Release
        run: cargo build --target x86_64-apple-darwin --release

      - name: Archive
        id: archive
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          mv target/x86_64-apple-darwin/release/ezkl ezkl-$VERSION-x86_64-apple-darwin
          tar czvf ezkl-$VERSION-x86_64-apple-darwin.tar.gz ezkl-$VERSION-x86_64-apple-darwin
          echo "::set-output name=path::$(pwd)/ezkl-$VERSION-x86_64-apple-darwin.tar.gz"

      - name: Create Release
        run: |
          gh release create $VERSION --title "Release $VERSION" --notes "Release $VERSION"
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Upload Release Asset
        run: |
          gh release upload $VERSION ${{ steps.archive.outputs.path }}
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
