name: ezkl-lib-release
on:
  push:
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-musl
          toolchain: stable
          override: true

      - name: Install Cross
        run: cargo install cross

      - name: Build Release
        run: cross build --target x86_64-unknown-linux-musl --release

      - name: Archive
        id: archive
        run: |
          mv target/x86_64-unknown-linux-musl/release/ezkl ezkl-x86_64-unknown-linux-musl
          tar czvf ezkl-x86_64-unknown-linux-musl.tar.gz ezkl-x86_64-unknown-linux-musl
          echo "::set-output name=path::$(pwd)/ezkl-x86_64-unknown-linux-musl.tar.gz"

      - name: Setup GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Create Release
        run: |
          gh auth login --with-token <<< "${{ secrets.RELEASE_TOKEN }}"
          gh release create 0.4.7 --title "Release 0.4.7" --notes "Release 0.4.7"
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Upload Release Asset
        run: |
          gh release upload 0.4.7 ${{ steps.archive.outputs.path }}
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-pc-windows-msvc
          toolchain: stable
          override: true

      - name: Build Release
        run: cargo build --target x86_64-pc-windows-msvc --release

      - name: Archive
        id: archive
        run: |
          mv target/x86_64-pc-windows-msvc/release/ezkl.exe ezkl-t-x86_64-pc-windows-msvc.exe
          7z a ezkl-t-x86_64-pc-windows-msvc.zip ezkl-t-x86_64-pc-windows-msvc.exe
          echo "::set-output name=path::$(pwd)/ezkl-t-x86_64-pc-windows-msvc.zip"

      - name: Create Release
        run: |
          gh auth login --with-token <<< "${{ secrets.RELEASE_TOKEN }}"
          gh release create 0.4.7 --title "Release 0.4.7" --notes "Release 0.4.7"
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Upload Release Asset
        run: |
          gh release upload 0.4.7 ${{ steps.archive.outputs.path }}
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-apple-darwin
          toolchain: stable
          override: true

      - name: Build Release
        run: cargo build --target x86_64-apple-darwin --release

      - name: Archive
        id: archive
        run: |
          mv target/x86_64-apple-darwin/release/ezkl ezkl-t-x86_64-apple-darwin
          tar czvf ezkl-t-x86_64-apple-darwin.tar.gz ezkl-t-x86_64-apple-darwin
          echo "::set-output name=path::$(pwd)/ezkl-t-x86_64-apple-darwin.tar.gz"

      - name: Setup GitHub CLI
        run: |
          brew install gh

      - name: Create Release
        run: |
          gh auth login --with-token <<< "${{ secrets.RELEASE_TOKEN }}"
          gh release create 0.4.7 --title "Release 0.4.7" --notes "Release 0.4.7"
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Upload Release Asset
        run: |
          gh release upload 0.4.7 ${{ steps.archive.outputs.path }}
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
