name: Create New Release of iOS EZKL Package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to release"
        required: true
  push:
    tags:
      - "*"

jobs:
  build-and-update:
    runs-on: macos-latest

    steps:
      - name: Checkout EZKL
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build EzklCoreBindings
        run: CONFIGURATION=release cargo run --bin ios_gen_bindings --features ios-bindings

      - name: Clone ezkl-ios-port repository
        run: |
          git clone -b feat/ezkl-direct-integration https://github.com/${{ vars.SWIFT_PACKAGE_OWNER_USERNAME }}/ezkl-ios-port.git

      - name: Copy EzklCoreBindings
        run: |
          rm -rf ezkl-ios-port/Sources/EzklCoreBindings
          cp -r EzklCoreBindings ezkl-ios-port/Sources/

      - name: Set up Xcode environment
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Run Package Tests
        run: |
          cd ezkl-ios-port
          xcodebuild test \
            -scheme EzklPackage \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
            -resultBundlePath ../testResults

      - name: Run Example App Tests
        run: |
          cd ezkl-ios-port/Example
          xcodebuild test \
            -project Example.xcodeproj \
            -scheme EzklApp \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
            -parallel-testing-enabled NO \
            -resultBundlePath ../../exampleTestResults \
            -skip-testing:EzklAppUITests/EzklAppUITests/testButtonClicksInOrder

      - name: Upload Test Results (Package)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: package-test-results
          path: ./testResults

      - name: Upload Test Results (Example)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: example-app-test-results
          path: ./exampleTestResults

      - name: Commit and Push Changes to feat/ezkl-direct-integration
        run: |
          cd ezkl-ios-port
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add Sources/EzklCoreBindings
          git commit -m "Update EzklCoreBindings from ezkl-ios-rust-porter"
          git tag ${{ github.event.inputs.tag }}
          git remote set-url origin https://${SWIFT_PACKAGE_OWNER_USERNAME}:${EZKL_PORTER_TOKEN}@github.com/${SWIFT_PACKAGE_OWNER_USERNAME}/ezkl-ios-port.git
          git push origin feat/ezkl-direct-integration
          git push origin --tags
        env:
          EZKL_PORTER_TOKEN: ${{ secrets.EZKL_PORTER_TOKEN }}
          SWIFT_PACKAGE_OWNER_USERNAME: ${{ vars.SWIFT_PACKAGE_OWNER_USERNAME }}